<?php
namespace StepSystem\Controllers;
use StepSystem\Core\View;use StepSystem\Core\Auth;use StepSystem\Core\Database;use StepSystem\Core\Flash;use StepSystem\Models\User;use StepSystem\Services\AdminLog;use StepSystem\Services\Setting;use StepSystem\Services\StepRunner;
class AdminController{
 public function index(){Auth::requireAdmin();$p=Database::pdo();$q=trim($_GET['q']??'');$page=max(1,(int)($_GET['page']??1));$size=5;$where='';$args=[];if($q!==''){$where=' WHERE username LIKE ?';$args[]='%'.$q.'%';}$s=$p->prepare('SELECT COUNT(*) FROM users'.$where);$s->execute($args);$total=(int)$s->fetchColumn();$active=(int)$p->query('SELECT COUNT(*) FROM users WHERE status=1')->fetchColumn();$exp=0;foreach($p->query("SELECT expires_at FROM users WHERE role='user' AND expires_at IS NOT NULL") as $r)if(Auth::expired($r['expires_at']))$exp++;$pages=max(1,ceil($total/$size));$page=min($page,$pages);$sql='SELECT * FROM users'.$where.' ORDER BY id DESC LIMIT '.$size.' OFFSET '.(($page-1)*$size);$s=$p->prepare($sql);$s->execute($args);View::render('admin/users',['title'=>'管理后台','users'=>$s->fetchAll(),'total'=>$total,'active'=>$active,'exp'=>$exp,'q'=>$q,'page'=>$page,'pages'=>$pages]);}
 public function save($x=null){Auth::requireAdmin();$edit=$x!==null;if($_SERVER['REQUEST_METHOD']==='POST'){$n=trim($_POST['username']??'');$pw=trim($_POST['password']??'');$role=$_POST['role']==='admin'?'admin':'user';$st=(int)($_POST['status']??1)===1?1:0;$ex=trim($_POST['expires_at']??'');$ex=$ex?str_replace('T',' ',$ex).(strlen($ex)===16?':00':''):null;if(!$edit&&strlen($pw)<6){Flash::set('新用户密码至少 6 位','error');redirect('index.php?r=admin_create');}$data=['username'=>$n,'role'=>$role,'status'=>$st,'expires_at'=>$role==='admin'?null:$ex];if($pw!=='')$data['password']=password_hash($pw,PASSWORD_DEFAULT);if($edit){User::update($x['id'],$data);AdminLog::write('update_user','ID '.$x['id']);Flash::set('用户已更新');}else{User::create($n,$pw,$role,$role==='admin'?null:$ex,$st);AdminLog::write('create_user',$n);Flash::set('用户已创建');}redirect('index.php?r=admin');}View::render('admin/edit',['title'=>$edit?'编辑用户':'新增用户','x'=>$x]);}
 public function delete(){Auth::requireAdmin();if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit('Method Not Allowed');}if(!hash_equals($_SESSION['csrf_token']??'',(string)($_POST['csrf_token']??''))){http_response_code(403);exit('CSRF validation failed');}$id=(int)($_POST['id']??0);if($id===(int)Auth::user()['id']){Flash::set('不能删除自己','error');redirect('index.php?r=admin');}User::delete($id);AdminLog::write('delete_user','ID '.$id);Flash::set('用户已删除');redirect('index.php?r=admin');}
 public function logs(){Auth::requireAdmin();$p=Database::pdo();$id=(int)($_GET['id']??0);$u=User::find($id);if(!$u){Flash::set('用户不存在','error');redirect('index.php?r=admin');}$page=max(1,(int)($_GET['page']??1));$size=10;$s=$p->prepare('SELECT COUNT(*) FROM step_logs WHERE user_id=?');$s->execute([$id]);$total=(int)$s->fetchColumn();$pages=max(1,(int)ceil($total/$size));$page=min($page,$pages);$s=$p->prepare('SELECT * FROM step_logs WHERE user_id=? ORDER BY id DESC LIMIT '.$size.' OFFSET '.(($page-1)*$size));$s->execute([$id]);View::render('admin/user_logs',['title'=>'用户日志','x'=>$u,'logs'=>$s->fetchAll(),'page'=>$page,'pages'=>$pages,'total'=>$total]);}
 public function adminUsername(){Auth::requireAdmin();$p=Database::pdo();$admin=Auth::user();if(($admin['role']??'')!=='admin'){Flash::set('无管理员权限','error');redirect('index.php?r=dashboard');}if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals($_SESSION['csrf_token']??'',(string)($_POST['csrf_token']??''))){http_response_code(403);exit('CSRF validation failed');}$username=trim((string)($_POST['username']??''));if(mb_strlen($username)<3||mb_strlen($username)>64){Flash::set('管理员用户名长度需为 3-64 位','error');redirect('index.php?r=admin_username');}$s=$p->prepare('SELECT id FROM users WHERE username=? AND id<>? LIMIT 1');$s->execute([$username,$admin['id']]);if($s->fetch()){Flash::set('该用户名已存在，请换一个','error');redirect('index.php?r=admin_username');}$old=$admin['username'];$u=$p->prepare('UPDATE users SET username=? WHERE id=? AND role=\'admin\'');$u->execute([$username,$admin['id']]);AdminLog::write('update_admin_username',$old.' -> '.$username);Auth::refresh();Flash::set('管理员用户名已修改');redirect('index.php?r=admin');}View::render('admin/admin_username',['title'=>'修改管理员用户名','admin'=>$admin]);}
 public function registerSettings(){Auth::requireAdmin();$defs=['registration_enabled'=>'1','registration_gift_days'=>'7'];if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals($_SESSION['csrf_token']??'',(string)($_POST['csrf_token']??''))){http_response_code(403);exit('CSRF validation failed');}$enabled=isset($_POST['registration_enabled'])?'1':'0';$days=max(0,min(36500,(int)($_POST['registration_gift_days']??0)));Setting::setMany(['registration_enabled'=>$enabled,'registration_gift_days'=>(string)$days]);AdminLog::write('register_settings','enabled='.$enabled.' days='.$days);Flash::set('注册设置已保存');redirect('index.php?r=admin_register_settings');}$cfg=Setting::getMany($defs);View::render('admin/register_settings',['title'=>'注册设置','cfg'=>$cfg]);}
 public function proxy(){Auth::requireAdmin();$defs=self::proxyDefaults();if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals($_SESSION['csrf_token']??'',(string)($_POST['csrf_token']??''))){http_response_code(403);exit('CSRF validation failed');}$data=[];foreach($defs as $k=>$v)$data[$k]=trim((string)($_POST[$k]??''));$data['proxy_enabled']=isset($_POST['proxy_enabled'])?'1':'0';$data['whitelist_enabled']=isset($_POST['whitelist_enabled'])?'1':'0';$data['cooldown_seconds']=(string)max(0,(int)$data['cooldown_seconds']);$data['retry_count']=(string)max(0,min(5,(int)$data['retry_count']));Setting::setMany($data);AdminLog::write('proxy_settings','update');Flash::set('代理设置已保存');redirect('index.php?r=admin_proxy');}$cfg=Setting::getMany($defs);$ip=StepRunner::detectPublicIp();View::render('admin/proxy',['title'=>'代理设置','cfg'=>$cfg,'publicIp'=>$ip]);}
 public function proxyTest(){Auth::requireAdmin();$res=StepRunner::proxyDiagnostics();header('Content-Type: application/json; charset=utf-8');echo json_encode($res,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT);}
 public function yhOAuthSettings(){Auth::requireAdmin();$defs=['yh_oauth_enabled'=>'1','yh_oauth_register_enabled'=>'1','yh_oauth_app_id'=>'','yh_oauth_app_key'=>'','yh_oauth_callback'=>default_yh_callback_url()];if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals($_SESSION['csrf_token']??'',(string)($_POST['csrf_token']??''))){http_response_code(403);exit('CSRF validation failed');}$data=[];foreach($defs as $k=>$v)$data[$k]=trim((string)($_POST[$k]??''));$data['yh_oauth_enabled']=isset($_POST['yh_oauth_enabled'])?'1':'0';$data['yh_oauth_register_enabled']=isset($_POST['yh_oauth_register_enabled'])?'1':'0';Setting::setMany($data);AdminLog::write('yh_oauth_settings','update');Flash::set('授权登录设置已保存');redirect('index.php?r=admin_yh_oauth');}$cfg=Setting::getMany($defs);View::render('admin/yh_oauth',['title'=>'授权登录设置','cfg'=>$cfg]);}
 private static function proxyDefaults(){return ['proxy_enabled'=>'1','proxy_api_url'=>getenv('STEP_PROXY_API_URL')?:'','whitelist_enabled'=>'1','whitelist_get_url'=>'','whitelist_add_url'=>'','whitelist_del_url'=>'','whitelist_memo'=>'step-system-nas','cooldown_seconds'=>'300','retry_count'=>'2','whitelist_heartbeat_seconds'=>'300'];}

}