<?php
namespace StepSystem\Controllers;
use StepSystem\Core\View;use StepSystem\Core\Auth;use StepSystem\Core\Flash;use StepSystem\Core\Database;use StepSystem\Services\StepRunner;
class StepController{
 private function pagedLogs($userId,$page=1,$perPage=5){$page=max(1,(int)$page);$perPage=max(1,min(20,(int)$perPage));$count=Database::pdo()->prepare('SELECT COUNT(*) FROM step_logs WHERE user_id=?');$count->execute([$userId]);$total=min(25,(int)$count->fetchColumn());$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);$offset=($page-1)*$perPage;$s=Database::pdo()->prepare('SELECT steps,status,message,created_at FROM step_logs WHERE user_id=? ORDER BY id DESC LIMIT '.$perPage.' OFFSET '.$offset);$s->execute([$userId]);return ['items'=>$s->fetchAll(),'page'=>$page,'pages'=>$pages,'total'=>$total,'perPage'=>$perPage];}
 private function writeLog($userId,$steps,$status,$message){$p=Database::pdo();$p->prepare('INSERT INTO step_logs(user_id,steps,status,message,created_at) VALUES(?,?,?,?,?)')->execute([$userId,$steps,$status,mb_substr($message,0,250),now()]);$p->prepare('DELETE FROM step_logs WHERE user_id=? AND id NOT IN (SELECT id FROM (SELECT id FROM step_logs WHERE user_id=? ORDER BY id DESC LIMIT 25) x)')->execute([$userId,$userId]);}
 public function settings(){Auth::requireLogin();$u=Auth::user();if($_SERVER['REQUEST_METHOD']==='POST'){$zu=trim($_POST['zepp_username']??'');$zp=(string)($_POST['zepp_password']??'');$min=max(1,(int)($_POST['step_min']??3000));$max=max(1,(int)($_POST['step_max']??8000));if($min>$max){Flash::set('步数范围不正确','error');redirect('index.php?r=step_settings');}$check=StepRunner::validateLogin($zu,$zp);if($check['status']!=='success'){Flash::set($check['message'],'error');redirect('index.php?r=step_settings');}$key=trim($_POST['run_key']??'');if($key==='')$key=bin2hex(random_bytes(16));$auto=!empty($_POST['auto_run'])?1:0;$time=trim($_POST['run_time']??'07:30');if(!preg_match('/^([01]\d|2[0-3]):[0-5]\d$/',$time))$time='07:30';$today=date('Y-m-d');$now=date('H:i');$lastRun=($auto&&$time<=$now)?$today:null;Database::pdo()->prepare('UPDATE users SET zepp_username=?,zepp_password=?,step_min=?,step_max=?,run_key=?,auto_run=?,run_time=?,last_step_run_date=? WHERE id=?')->execute([$zu,$zp,$min,$max,$key,$auto,$time,$lastRun,$u['id']]);$this->writeLog($u['id'],null,'success','步数配置保存成功：'.($auto?'已开启':'未开启').'定时执行，时间 '.$time.'，范围 '.$min.'-'.$max);Auth::refresh();Flash::set('步数配置已保存，提交日志已记录');redirect('index.php?r=step_settings');}View::render('step/settings',['title'=>'步数配置','user'=>Auth::user(),'logPage'=>$this->pagedLogs($u['id'],$_GET['log_page']??1,5)]);}
 public function test(){Auth::requireLogin();$res=StepRunner::run(Auth::user());Flash::set($res['message'],$res['status']==='success'?'success':'error');redirect('index.php?r=step_settings');}
 public function run(){header('Content-Type: application/json; charset=utf-8');$key=$_GET['key']??'';$s=Database::pdo()->prepare('SELECT * FROM users WHERE run_key=? LIMIT 1');$s->execute([$key]);$u=$s->fetch();if(!$u){http_response_code(403);echo json_encode(['code'=>403,'msg'=>'密钥错误'],JSON_UNESCAPED_UNICODE);return;}if((int)$u['status']!==1||($u['role']!=='admin'&&Auth::expired($u['expires_at']))){http_response_code(403);echo json_encode(['code'=>403,'msg'=>'账号不可用或已过期'],JSON_UNESCAPED_UNICODE);return;}$res=StepRunner::run($u);echo json_encode(['code'=>$res['status']==='success'?200:500,'msg'=>$res['message'],'data'=>['steps'=>$res['steps']]],JSON_UNESCAPED_UNICODE);}
}